sudo: required
services:
  - docker

before_install:
  - docker build -t rydberg123/movie-app .

script:
  - docker run rydberg123/movie-app mvn test

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push rydberg123/movie-app


deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "movie-app"
  env: "Movieapp-env"
  bucket_name: "elasticbeanstalk-eu-north-1-400794629169"
  bucket_path: "movie-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY